name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create ECR repositories
      run: |
        echo "Creating ECR repositories..."
        aws ecr create-repository --repository-name inventory-manager-backend --region ${{ secrets.AWS_REGION }} || echo "Backend repository already exists or creation failed"
        aws ecr create-repository --repository-name inventory-manager-frontend --region ${{ secrets.AWS_REGION }} || echo "Frontend repository already exists or creation failed"
        echo "Listing repositories to verify creation:"
        aws ecr describe-repositories --region ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_BACKEND: inventory-manager-backend
      run: |
        echo "Using ECR registry: $ECR_REGISTRY"
        echo "Building backend image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA ./inventory-manager-backend
        echo "Tagging backend image..."
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest
        echo "Pushing backend images..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$GITHUB_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:latest

    - name: Build and push frontend image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_FRONTEND: inventory-manager-frontend
      run: |
        echo "Building frontend image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA ./inventory-manager-frontend
        echo "Tagging frontend image..."
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest
        echo "Pushing frontend images..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$GITHUB_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get ECR Registry
      id: ecr-registry
      run: |
        # Get ECR registry URL first
        ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        echo "ECR Registry: $ECR_REGISTRY"

        # Login to ECR with specific registry
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY

        # Use the newer environment file approach
        echo "ecr-registry=$ECR_REGISTRY" >> "$GITHUB_OUTPUT"

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ./ec2_key.pem
        chmod 600 ./ec2_key.pem
        ECR_REGISTRY=${{ steps.ecr-registry.outputs.ecr-registry }}
        ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -i ./ec2_key.pem ec2-user@35.182.196.96 << EOF
        set -e
        # Login to ECR
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY

        # Pull latest images
        docker pull $ECR_REGISTRY/inventory-manager-backend:latest
        docker pull $ECR_REGISTRY/inventory-manager-frontend:latest

        # Stop and remove old containers if they exist
        docker-compose down || true

        # Create docker-compose.yml
        cat > docker-compose.yml <<EOL
        version: '3.8'
        services:
          backend:
            image: \$(ECR_REGISTRY)/inventory-manager-backend:latest
            ports:
              - "3000:3000"
            environment:
              - NODE_ENV=production
              - MONGODB_URI=mongodb+srv://shsu877:ODjnrJZrQ7aO4xHL@sticker-inventory.hbksle7.mongodb.net/inventory-manager?retryWrites=true&w=majority
            restart: unless-stopped

          frontend:
            image: \$(ECR_REGISTRY)/inventory-manager-frontend:latest
            ports:
              - "80:80"
            restart: unless-stopped
        EOL

        # Run the application in background and give it time to start
        echo "Starting containers..."
        docker-compose up -d
        echo "Waiting for containers to initialize..."
        sleep 10

        # Check container status and clean up concurrently
        echo "Checking container status..."
        docker-compose ps
        echo "Running cleanup in background..."
        (docker image prune -f || echo "Cleanup completed with warnings")
        echo "Deployment completed!"
        EOF